### ISSUE TITLE
Sorry, I meet a error when run the code.

### ISSUE THREAD

**Issue by simba0626** [AskNowQA/KrantikariQA#16]
Hi, Sorry to trouble you. I find a error: 
AttributeError: module 'datasetPreparation.entity_subgraph' has no attribute 'CreateSubgraph'

Would you like to help me?

yawei

**Comment by geraltofrivia** [comment]
Hi, could you provide a few details?

1. The entire traceback
2. Which file were you running when you got this error?
2. Which directory were you running the code from?

Thanks.

**Comment by simba0626** [comment]
Thanks. This problem is solved.  I made an error when download.

**Comment by haophancs** [comment]
Hi, could you please tell me how you solved this issue?

**Comment by geraltofrivia** [comment]
Hi, I'll try to help you out although in all honesty its been many years since I last saw this code base. Could you please let me know the specifics of the issue you're facing. To begin with, 

Could you provide a few details:

- The entire traceback
- Which file were you running when you got this error?
- Which directory were you running the code from?
- Which python version?

Thanks.

**Comment by haophancs** [comment]
Hi, I have solved this problem by reseting to your old commit of module datasetPreparation.entity_subgraph. In your latest commit you seemed to remove CreateSubgraph class by some reason. But other parts of your code still call it, e.g. datasetPreparation.create_dataset
